github: kilasuit         # GitHub Sponsors username(s)
# open_collective: # Open Collective handle
# ko_fi:           # Ko-fi username
# tidelift:        # Tidelift package name (e.g. npm/package-name)
custom:      https://blog.kilasuit.org/donation-policy/    # Array of custom sponsorship URLs
